export const USERDATA="USERDATA";
export const USERDATASUCCESS="USERDATASUCCESS";
export const USERDATAFAILURE="USERDATAFAILURE";

export const USERLOGIN = " USERLOGIN";
export const USERLOGINCHECK = " USERLOGINCHECK";
export const LOGINSUCCESS = " LOGINSUCCESS";
export const LOGINFAILURE = " LOGINFAILURE";

export const RESETPASSWORD = " RESETPASSWORD";
export const PASSWORDCHANGE="PASSWORDCHANGE"
export const PASSWORDCHANGESUCCESS="PASSWORDCHANGESUCCESS";
export const PASSWORDCHANGEFAILURE="PASSWORDCHANGEFAILURE";

export const NEWPASSWORD="NEWPASSWORD";
export const NEWPASSWORDSUBMIT="NEWPASSWORDSUBMIT";
export const NEWPASSWORDSUCCESS="NEWPASSWORDSUCCESS";
export const NEWPASSWORDFAILURE="NEWPASSWORDFAILURE";

export const BUTTON="BUTTON"
export const BUTTONFINAL="BUTTONFINAL"